name: Trigger Docs Update

# This workflow should be added to the OpenHands repository
# at .github/workflows/trigger-docs-update.yml

on:
  push:
    branches: [main]
    paths:
      - 'docs/**'
  
  pull_request:
    branches: [main]
    paths:
      - 'docs/**'
    types: [closed]

jobs:
  trigger-docs-update:
    # Only run on push to main or when PR is merged
    if: github.event_name == 'push' || (github.event.pull_request.merged == true)
    runs-on: ubuntu-latest
    
    steps:
      - name: Trigger docs repository update
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            try {
              await github.rest.repos.createDispatchEvent({
                owner: 'All-Hands-AI',
                repo: 'docs',
                event_type: 'update-docs',
                client_payload: {
                  source_repo: 'OpenHands',
                  ref: context.ref,
                  sha: context.sha
                }
              });
              
              console.log('Successfully triggered docs repository update');
            } catch (error) {
              console.error('Failed to trigger docs update:', error);
              // Don't fail the workflow if this fails
            }