name: Trigger Submodule Update

on:
  # This workflow can be triggered by other repositories
  repository_dispatch:
    types: [update-docs]

jobs:
  trigger-update:
    runs-on: ubuntu-latest
    
    steps:
      - name: Trigger submodule update
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'update-submodules.yml'
            });
            
            console.log('Triggered submodule update workflow');