name: Update Submodule

on:
  # Allow manual triggering
  workflow_dispatch:
  
  # Trigger via repository dispatch from source repos
  repository_dispatch:
    types: [update]
  
  # Schedule to check for updates daily (for repos we don't control)
  schedule:
    - cron: '0 6 * * *'  # Daily at 6 AM UTC

jobs:
  update:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: recursive
      
      - name: Update specific submodule
        if: github.event.client_payload.module
        run: |
          git submodule update --init --recursive --checkout -f --remote -- "${{ github.event.client_payload.module }}"
          git config --global user.name "GitHub Action"
          git config --global user.email "noreply@github.com"
          
          # Check if there are any changes
          if git diff --quiet --exit-code; then
            echo "No submodule updates available for ${{ github.event.client_payload.module }}"
            exit 0
          fi
          
          git commit -am "deploy: ${{ github.event.client_payload.module }} - ${{ github.event.client_payload.sha }}"
          git push
      
      - name: Update all submodules (scheduled run)
        if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
        run: |
          git submodule update --remote --recursive
          git config --global user.name "GitHub Action"
          git config --global user.email "noreply@github.com"
          
          # Check if there are any changes
          if git diff --quiet --exit-code; then
            echo "No submodule updates available"
            exit 0
          fi
          
          git commit -am "chore: update all submodules to latest versions"
          git push