name: Sync docs folder

on:
  repository_dispatch:
    types: [update]
  workflow_dispatch:
    inputs:
      module:
        description: "Module/repo name (without owner), e.g. agent-sdk"
        required: true
      branch:
        description: "Branch to read from the source repo"
        required: false
        default: "main"
      ref:
        description: "Specific ref (SHA/tag/branch). Overrides branch if provided."
        required: false

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    env:
      TOKEN: ${{ secrets.ALLHANDS_BOT_GITHUB_PAT || secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Resolve inputs/env
        id: cfg
        shell: bash
        run: |
          set -euo pipefail
          EVENT="${{ github.event_name }}"
          SUBDIR="docs"
          if [[ "$EVENT" == "workflow_dispatch" ]]; then
            MODULE="${{ inputs.module }}"
            BRANCH="${{ inputs.branch || 'main' }}"
            REF="${{ inputs.ref || '' }}"
          else
            # repository_dispatch payload expected:
            # { "ref": "...", "sha": "...", "module": "agent-sdk", "branch": "main" }
            MODULE="${{ github.event.client_payload.module }}"
            BRANCH="${{ github.event.client_payload.branch || 'main' }}"
            REF="${{ github.event.client_payload.ref || '' }}"
          fi

          if [[ -z "${MODULE}" ]]; then
            echo "ERROR: module is required (inputs.module or client_payload.module)" >&2
            exit 1
          fi

          OWNER="${{ github.repository_owner }}"
          SRC_REPO_URL="https://github.com/${OWNER}/${MODULE}.git"

          # Use REF if provided; else fall back to branch
          [[ -z "${REF}" ]] && REF="${BRANCH}"

          DEST_PREFIX="${MODULE,,}"  # lowercase module name as dest prefix
          echo "SRC_REPO_URL=$SRC_REPO_URL"   >> "$GITHUB_OUTPUT"
          echo "REF=$REF"                     >> "$GITHUB_OUTPUT"
          echo "SUBDIR=$SUBDIR"               >> "$GITHUB_OUTPUT"
          echo "DEST_PREFIX=$DEST_PREFIX"     >> "$GITHUB_OUTPUT"
          echo "MODULE=$MODULE"               >> "$GITHUB_OUTPUT"

      - name: Configure Git author
        run: |
          git config user.name "all-hands-bot"
          git config user.email "contact@all-hands.dev"

      - name: Fetch only ${{ steps.cfg.outputs.SUBDIR }} via sparse-checkout
        env:
          SRC_REPO_URL: ${{ steps.cfg.outputs.SRC_REPO_URL }}
          REF: ${{ steps.cfg.outputs.REF }}
          SUBDIR: ${{ steps.cfg.outputs.SUBDIR }}
          TOKEN: ${{ env.TOKEN }}
        shell: bash
        run: |
          set -euo pipefail
          tmpdir="$(mktemp -d)"
          echo "Using temp dir: $tmpdir"

          # Authenticated URL for private repos
          auth_url="$SRC_REPO_URL"
          if [[ "$auth_url" == https://github.com/* && -n "${TOKEN:-}" ]]; then
            auth_url="${auth_url/https:\/\/github.com/https:\/\/x-access-token:${TOKEN}@github.com}"
          fi

          # Init + sparse-checkout only SUBDIR
          git -C "$tmpdir" init -q src
          git -C "$tmpdir/src" remote add origin "$auth_url"
          git -C "$tmpdir/src" config core.sparseCheckout true
          git -C "$tmpdir/src" sparse-checkout init --cone
          git -C "$tmpdir/src" sparse-checkout set "$SUBDIR"
          git -C "$tmpdir/src" fetch --depth=1 origin "$REF"
          git -C "$tmpdir/src" checkout -q FETCH_HEAD

          if [[ ! -d "$tmpdir/src/$SUBDIR" ]]; then
            echo "ERROR: '$SUBDIR' not found at $SRC_REPO_URL@$REF" >&2
            exit 1
          fi

          echo "TMPDIR=$tmpdir" >> "$GITHUB_ENV"

      - name: Sync into repo root at ${{ steps.cfg.outputs.DEST_PREFIX }} (flatten docs/ -> module/)
        env:
          TMPDIR: ${{ env.TMPDIR }}
          SUBDIR: ${{ steps.cfg.outputs.SUBDIR }}
          DEST_PREFIX: ${{ steps.cfg.outputs.DEST_PREFIX }}
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p "$DEST_PREFIX"

          # Mirror (add/update/delete) files from SUBDIR/* into DEST_PREFIX/
          # Exclude VCS bits and common CI folders from upstream to avoid noise
          rsync -a --delete \
            --exclude='.git/' \
            --exclude='.github/' \
            --exclude='.gitignore' \
            "$TMPDIR/src/$SUBDIR/" "$DEST_PREFIX/"

          # Optional: ensure a folder exists in git if upstream docs is empty
          if [ -z "$(ls -A "$DEST_PREFIX")" ]; then
            touch "$DEST_PREFIX/.gitkeep"
          fi

          # Stage changes for commit
          git add -A "$DEST_PREFIX"

      - name: Commit and push if changed
        env:
          MODULE: ${{ steps.cfg.outputs.MODULE }}
        shell: bash
        run: |
          set -euo pipefail
          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi
          SRC_SHA="${{ github.event.client_payload.sha || '' }}"
          REF_STR="${{ github.event.client_payload.ref || inputs.ref || inputs.branch || '' }}"
          git commit -m "vendor(copy): ${MODULE} ${REF_STR} ${SRC_SHA}"
          git push
